name: Daily Schedule

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 00:00 执行

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests ics pytz

      - name: Run script
        run: |
          python update_calendar.py
