name: Generate Calendar

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate_calendar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests ics pytz

    - name: Run script
      run: |
        python path/to/your_script.py

    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: calendar-results
        path: |
          data/
