name: Run Script and Update Files

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # 每天午夜运行一次

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests ics pytz

    - name: Run update script
      run: python chocobo_house.py

    - name: List files in the workspace
      run: |
        echo "Listing files in the workspace:"
        ls -R

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add data/ # 添加你的生成文件所在目录
        git commit -m "Update generated files" || echo "No changes to commit"
        git push
