      run: |
        python -m pip install --upgrade pip
        pip install requests ics
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests ics pytz  # 添加 pytz 库
        
    - name: Run update script
      run: python chocobo_house.py
